[package]
name = "halftone-processor"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3.69", features = ["ImageData", "HtmlCanvasElement", "CanvasRenderingContext2d"] }
